name: Final Diagnostic

on:
  workflow_dispatch:

jobs:
  diagnostic:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests
          
      - name: Run diagnostic
        run: |
          cat > diagnostic.py << 'EOF'
          import requests
          import time
          from datetime import datetime, timedelta
          
          BASE_URL = "https://api.hh.ru/vacancies"
          
          # Используем тот же User-Agent, что и в вашем парсере!
          HEADERS = {
              'User-Agent': 'VacancyParser/1.0 (contact@example.com)'
          }
          
          print("=" * 70)
          print("ДИАГНОСТИКА ОГРАНИЧЕНИЙ API HH.RU")
          print(f"Время: {datetime.now()}")
          print("=" * 70)
          
          # Первый запрос
          params = {
              'text': 'системный администратор',
              'area': '1',
              'search_field': 'name',
              'per_page': '50',
              'page': '0'
          }
          
          print("\n1. АНАЛИЗ БАЗОВОГО ЗАПРОСА")
          print("-" * 70)
          
          try:
              response = requests.get(BASE_URL, params=params, headers=HEADERS, timeout=30)
              print(f"HTTP статус: {response.status_code}")
              
              if response.status_code == 200:
                  data = response.json()
                  found = data.get('found', 0)
                  pages = data.get('pages', 0)
                  per_page = data.get('per_page', 0)
                  items = len(data.get('items', []))
                  
                  print(f"✅ Найдено вакансий: {found}")
                  print(f"📄 Страниц доступно: {pages}")
                  print(f"📏 На страницу: {per_page}")
                  print(f"📦 На первой странице: {items}")
                  print(f"🔢 Макс. доступно: {min(pages * per_page, 2000)}")
                  
                  # Тест критических страниц
                  print("\n2. ТЕСТ ГЛУБИНЫ ПАГИНАЦИИ")
                  print("-" * 70)
                  
                  test_pages = [0, 5, 9, 10, 15, 19, 20, 25]
                  last_working = 0
                  total_items = 0
                  
                  for p in test_pages:
                      if p > pages:
                          break
                          
                      params['page'] = str(p)
                      time.sleep(0.3)
                      
                      try:
                          r = requests.get(BASE_URL, params=params, headers=HEADERS, timeout=30)
                          if r.status_code == 200:
                              d = r.json()
                              count = len(d.get('items', []))
                              if count > 0:
                                  last_working = p
                                  total_items += count
                                  print(f"✅ Страница {p}: {count} вакансий")
                              else:
                                  print(f"⚠️ Страница {p}: пустая")
                          else:
                              print(f"❌ Страница {p}: HTTP {r.status_code}")
                      except Exception as e:
                          print(f"❌ Страница {p}: {str(e)[:50]}")
                  
                  # Анализ
                  print(f"\n3. РЕЗУЛЬТАТЫ")
                  print("-" * 70)
                  print(f"Последняя рабочая страница: {last_working}")
                  print(f"Максимальный offset: {last_working * 50 + 50}")
                  
                  if last_working == 19:
                      print("🚫 ПОДТВЕРЖДЕН ЛИМИТ: offset ≤ 1000")
                      print("   При per_page=50 доступно максимум 20 страниц (0-19)")
                      print(f"   Теряется: {found - 1000} вакансий из {found}")
                  
                  # Тест сегментации
                  print("\n4. ПРОВЕРКА СЕГМЕНТАЦИИ ПО ДАТАМ")
                  print("-" * 70)
                  
                  date_ranges = [
                      (0, 1, "Сегодня"),
                      (1, 3, "1-3 дня"),
                      (3, 7, "3-7 дней"),
                      (7, 14, "Неделя-2 недели"),
                      (14, 30, "2 недели-месяц")
                  ]
                  
                  total_segmented = 0
                  
                  for start, end, name in date_ranges:
                      date_from = (datetime.now() - timedelta(days=end)).strftime('%Y-%m-%d')
                      date_to = (datetime.now() - timedelta(days=start)).strftime('%Y-%m-%d')
                      
                      p = {
                          'text': 'системный администратор',
                          'area': '1',
                          'search_field': 'name',
                          'date_from': date_from,
                          'date_to': date_to,
                          'per_page': '50',
                          'page': '0'
                      }
                      
                      r = requests.get(BASE_URL, params=p, headers=HEADERS, timeout=30)
                      if r.status_code == 200:
                          d = r.json()
                          f = d.get('found', 0)
                          pg = d.get('pages', 0)
                          total_segmented += f
                          
                          status = "✅" if pg <= 20 else "⚠️"
                          print(f"{status} {name}: {f} вакансий ({pg} стр.)")
                      
                      time.sleep(0.3)
                  
                  print(f"\n📊 Всего через сегменты: ~{total_segmented}")
                  print("   (с учетом пересечений)")
                  
                  if total_segmented > found:
                      print("✅ Сегментация поможет получить все вакансии!")
                  
              else:
                  print(f"❌ Ошибка: {response.text}")
                  
          except Exception as e:
              print(f"❌ Критическая ошибка: {e}")
          
          print("\n" + "=" * 70)
          print("ДИАГНОСТИКА ЗАВЕРШЕНА")
          print("=" * 70)
          EOF
          
          python diagnostic.py
