name: Working Diagnostic

on:
  workflow_dispatch:

jobs:
  diagnostic:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests
          
      - name: Run diagnostic
        run: |
          cat > diagnostic.py << 'EOF'
          import requests
          import time
          from datetime import datetime, timedelta
          
          BASE_URL = "https://api.hh.ru/vacancies"
          
          # User-Agent из вашего рабочего файла update-vacancies.yml
          HEADERS = {
              'User-Agent': 'VacancyAggregator/2.0 (https://gradelift.ru)'
          }
          
          print("=" * 70)
          print("ДИАГНОСТИКА ОГРАНИЧЕНИЙ API HH.RU")
          print(f"Время: {datetime.now()}")
          print("=" * 70)
          
          # Первый запрос
          params = {
              'text': 'системный администратор',
              'area': '1',
              'search_field': 'name',
              'per_page': '50',
              'page': '0'
          }
          
          print("\n1. АНАЛИЗ БАЗОВОГО ЗАПРОСА")
          print("-" * 70)
          
          try:
              response = requests.get(BASE_URL, params=params, headers=HEADERS, timeout=30)
              print(f"HTTP статус: {response.status_code}")
              
              if response.status_code == 200:
                  data = response.json()
                  found = data.get('found', 0)
                  pages = data.get('pages', 0)
                  per_page = data.get('per_page', 0)
                  items = len(data.get('items', []))
                  
                  print(f"✅ Найдено вакансий: {found}")
                  print(f"📄 Страниц доступно: {pages}")
                  print(f"📏 На страницу: {per_page}")
                  print(f"📦 На первой странице: {items}")
                  print(f"🔢 Теоретически доступно: {pages * per_page}")
                  
                  # Тест критических страниц
                  print("\n2. ТЕСТ ГЛУБИНЫ ПАГИНАЦИИ")
                  print("-" * 70)
                  
                  # Проверяем страницы около предполагаемого лимита
                  test_pages = []
                  if pages > 30:
                      test_pages = [0, 5, 9, 10, 15, 19, 20, 25, 29, 30]
                  elif pages > 20:
                      test_pages = [0, 5, 9, 10, 15, 19, 20, pages-1]
                  else:
                      test_pages = list(range(0, min(pages, 25)))
                  
                  last_working = 0
                  total_collected = 0
                  empty_pages = []
                  
                  for p in test_pages:
                      params['page'] = str(p)
                      time.sleep(0.3)
                      
                      try:
                          r = requests.get(BASE_URL, params=params, headers=HEADERS, timeout=30)
                          if r.status_code == 200:
                              d = r.json()
                              count = len(d.get('items', []))
                              if count > 0:
                                  last_working = p
                                  total_collected += count
                                  print(f"✅ Страница {p:2d}: {count:2d} вакансий (offset {p*50})")
                              else:
                                  empty_pages.append(p)
                                  print(f"⚠️ Страница {p:2d}: ПУСТАЯ (offset {p*50})")
                          else:
                              print(f"❌ Страница {p:2d}: HTTP {r.status_code}")
                      except Exception as e:
                          print(f"❌ Страница {p:2d}: {str(e)[:50]}")
                  
                  # Анализ результатов
                  print(f"\n3. АНАЛИЗ РЕЗУЛЬТАТОВ")
                  print("-" * 70)
                  print(f"Всего страниц по API: {pages}")
                  print(f"Последняя рабочая страница: {last_working}")
                  print(f"Максимальный рабочий offset: {last_working * 50 + 50}")
                  print(f"Собрано в тесте: {total_collected} вакансий")
                  
                  if empty_pages:
                      first_empty = min(empty_pages)
                      print(f"\nПервая пустая страница: {first_empty} (offset {first_empty * 50})")
                      if first_empty == 20:
                          print("🚫 ПОДТВЕРЖДЕН ЛИМИТ: offset = 1000 (20 страниц)")
                      elif first_empty == 10:
                          print("🚫 ПОДТВЕРЖДЕН ЛИМИТ: offset = 500 (10 страниц)")
                  
                  max_available = (last_working + 1) * 50
                  lost = found - max_available
                  print(f"\n📊 ИТОГО:")
                  print(f"   Найдено: {found}")
                  print(f"   Доступно через API: {max_available}")
                  print(f"   Недоступно: {lost} ({(lost/found*100):.1f}%)")
                  
                  # Тест альтернативных параметров
                  print("\n4. ТЕСТ С per_page=100")
                  print("-" * 70)
                  
                  params2 = params.copy()
                  params2['per_page'] = '100'
                  params2['page'] = '0'
                  
                  r = requests.get(BASE_URL, params=params2, headers=HEADERS, timeout=30)
                  if r.status_code == 200:
                      d = r.json()
                      print(f"✅ per_page=100 работает")
                      print(f"   Страниц: {d.get('pages', 0)}")
                      print(f"   На первой: {len(d.get('items', []))}")
                  else:
                      print(f"❌ per_page=100 не работает: HTTP {r.status_code}")
                  
                  # Проверка сегментации
                  print("\n5. ТЕСТ СЕГМЕНТАЦИИ ПО ДАТАМ")
                  print("-" * 70)
                  
                  segments = [
                      (1, "За последние 24 часа"),
                      (3, "За последние 3 дня"),
                      (7, "За последнюю неделю")
                  ]
                  
                  for days, name in segments:
                      date_from = (datetime.now() - timedelta(days=days)).strftime('%Y-%m-%d')
                      date_to = datetime.now().strftime('%Y-%m-%d')
                      
                      p = {
                          'text': 'системный администратор',
                          'area': '1',
                          'search_field': 'name',
                          'date_from': date_from,
                          'date_to': date_to,
                          'per_page': '50',
                          'page': '0'
                      }
                      
                      r = requests.get(BASE_URL, params=p, headers=HEADERS, timeout=30)
                      if r.status_code == 200:
                          d = r.json()
                          f = d.get('found', 0)
                          pg = d.get('pages', 0)
                          
                          if pg <= 20:
                              print(f"✅ {name}: {f} вакансий ({pg} стр.) - ОК")
                          else:
                              print(f"⚠️ {name}: {f} вакансий ({pg} стр.) - нужна доп. сегментация")
                      
                      time.sleep(0.3)
                  
              else:
                  print(f"❌ Ошибка: {response.text}")
                  
          except Exception as e:
              print(f"❌ Критическая ошибка: {e}")
          
          print("\n" + "=" * 70)
          print("ДИАГНОСТИКА ЗАВЕРШЕНА")
          print("=" * 70)
          EOF
          
          python diagnostic.py
